-- Optional starter catalog. Run after schema.sql.
insert into public.products
  (name, name_en, price, description, description_en, category, subcategory, in_stock, featured, is_active)
values
  (
    'Bó Hồng Đỏ Size Nhỏ 1',
    'Small Red Rose Bouquet 1',
    500000,
    'Bó hồng đỏ size nhỏ với giấy gói đen và nơ đỏ, gọn gàng nhưng vẫn nổi bật cho lời nhắn yêu thương.',
    'A small red rose bouquet wrapped in black paper with a red ribbon, simple, bold, and romantic.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    true,
    true
  ),
  (
    'Bó Hồng Đỏ Size Vừa 1',
    'Medium Red Rose Bouquet 1',
    850000,
    'Bó hồng đỏ size vừa trong giấy gói trắng, điểm hoa xanh nhỏ và thiệp nhắn tinh tế.',
    'A medium red rose bouquet in crisp white wrap, finished with a small blue accent and message card.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Vừa 2',
    'Medium Red Rose Bouquet 2',
    850000,
    'Bó hồng đỏ tròn đầy trong giấy gói trắng, tối giản và hiện đại cho dịp yêu thương.',
    'A full red rose bouquet in clean white wrap, minimal and modern for a romantic moment.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Vừa 3',
    'Medium Red Rose Bouquet 3',
    850000,
    'Bó hồng đỏ giấy đen với điểm lan trắng, sang trọng và nổi bật nhưng vẫn rất gọn.',
    'Red roses in black wrap with a white orchid accent, elegant, bold, and neatly styled.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Vừa 4',
    'Medium Red Rose Bouquet 4',
    850000,
    'Bó hồng đỏ phối lá xanh trong giấy gói nâu be, ấm áp và tự nhiên.',
    'Red roses with soft greenery in warm beige wrap, natural, modern, and heartfelt.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Lớn 1',
    'Large Red Rose Bouquet 1',
    1000000,
    'Bó hồng đỏ size lớn phối baby trắng trong giấy gói đen, nổi bật và sang trọng.',
    'A large red rose bouquet with white baby''s breath in black wrap, bold and elegant.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Lớn 2',
    'Large Red Rose Bouquet 2',
    1000000,
    'Bó hồng đỏ size lớn trong giấy gói đen, dáng cao hiện đại với nơ đỏ nổi bật.',
    'A large red rose bouquet in black wrap, styled tall and modern with a striking red ribbon.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Lớn 3',
    'Large Red Rose Bouquet 3',
    1000000,
    'Bó hồng đỏ size lớn giấy đen với nơ mảnh, rực rỡ và hiện đại cho lời tỏ bày.',
    'A large red rose bouquet in black wrap with a slim ribbon, bright, modern, and romantic.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Đỏ Size Lớn 4',
    'Large Red Rose Bouquet 4',
    1000000,
    'Bó hồng đỏ size lớn dáng tròn trong giấy gói đen, tối giản và đầy đặn.',
    'A large round red rose bouquet in black wrap, minimal, full, and polished.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó 100 Hoa Hồng Đỏ',
    '100 Red Rose Bouquet',
    2000000,
    'Bó 100 hoa hồng đỏ trong giấy gói đen, rực rỡ và thật ấn tượng cho khoảnh khắc đặc biệt.',
    'A 100-red-rose bouquet in black wrap, dramatic, romantic, and made for a special moment.',
    'Regular Bouquets',
    'Bo Hong Do',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Mini 1',
    'Mini Pink Rose Bouquet 1',
    100000,
    'Bó hồng phấn mini với ba bông hồng nhẹ nhàng trong giấy gói trắng, nhỏ xinh và tinh tế.',
    'A mini pink rose bouquet with three soft roses in white wrap, sweet, simple, and delicate.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Nhỏ 1',
    'Small Pink Rose Bouquet 1',
    300000,
    'Bó hồng phấn size nhỏ phối hoa trắng và lá xanh, tươi sáng trong giấy gói trắng.',
    'A small pink rose bouquet with white blooms and fresh greenery, bright in clean white wrap.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Nhỏ 2',
    'Small Pink Rose Bouquet 2',
    500000,
    'Bó hồng phấn size nhỏ đầy đặn với hoa trắng xanh, mềm mại trong lớp gói trong hiện đại.',
    'A fuller small pink rose bouquet with white-green accents, softly wrapped in modern clear paper.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Lớn 1',
    'Large Pink Rose Bouquet 1',
    1000000,
    'Bó hồng phấn size lớn trong giấy gói trắng, tròn đầy với nơ hồng mềm mại.',
    'A large pink rose bouquet in white wrap, full and rounded with a soft pink ribbon.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Lớn 2',
    'Large Pink Rose Bouquet 2',
    1000000,
    'Bó hồng phấn size lớn trong giấy gói trắng, sáng nhẹ và thanh lịch.',
    'A large pink rose bouquet in airy white wrap, soft, bright, and elegant.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Lớn 3',
    'Large Pink Rose Bouquet 3',
    1000000,
    'Bó hồng phấn size lớn dáng tròn, phủ sắc hồng dịu trong lớp gói trắng hiện đại.',
    'A large round pink rose bouquet, softly toned and framed in modern white wrap.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Lớn 4',
    'Large Pink Rose Bouquet 4',
    1000000,
    'Bó hồng phấn size lớn với giấy gói hồng và lưới mềm, ngọt ngào nhưng vẫn sang.',
    'A large pink rose bouquet with pink wrap and soft mesh, sweet yet polished.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Hồng Phấn Size Lớn 5',
    'Large Pink Rose Bouquet 5',
    1000000,
    'Bó hồng phấn size lớn dáng tròn gọn, phối nơ hồng và giấy trắng tinh tế.',
    'A large compact round pink rose bouquet with a pink ribbon and refined white wrap.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó 100 Hoa Hồng Phấn',
    '100 Pink Rose Bouquet',
    2000000,
    'Bó 100 hoa hồng phấn trong giấy gói đen, thật lớn và lãng mạn cho dịp đặc biệt.',
    'A 100-pink-rose bouquet in black wrap, grand, romantic, and made for a special occasion.',
    'Regular Bouquets',
    'Bo Hong Phan',
    true,
    false,
    true
  ),
  (
    'Bó Cẩm Tú Nhỏ 1',
    'Small Hydrangea Bouquet 1',
    500000,
    'Bó cẩm tú nhỏ tông xanh lam và xanh non, mát mắt trong lớp gói trong nhẹ.',
    'A small hydrangea bouquet in soft blue and fresh green tones, airy in clear wrap.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Cẩm Tú Nhỏ 2',
    'Small Hydrangea Bouquet 2',
    500000,
    'Bó cẩm tú nhỏ tông xanh trắng, gọn nhẹ với giấy gói trong và nơ xanh nhạt.',
    'A small green-white hydrangea bouquet with clear wrap and a pale blue ribbon.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Hoa Mix Size Vừa 1',
    'Medium Mixed Bouquet 1',
    850000,
    'Bó hoa mix size vừa rực rỡ với hồng vàng, hoa hồng phấn và điểm xanh tươi.',
    'A medium mixed bouquet with yellow roses, blush blooms, and fresh green accents.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Hoa Mix Size Vừa 2',
    'Medium Mixed Bouquet 2',
    850000,
    'Bó hoa mix size vừa nhiều sắc màu, tươi vui với hồng, gerbera và hoa nhí trắng.',
    'A medium mixed bouquet full of color, with roses, gerberas, and tiny white daisies.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Nhỏ 1',
    'Small Pastel Mix Bouquet 1',
    500000,
    'Bó pastel mix size nhỏ tông hồng nổi bật trong giấy gói đen, hiện đại và ngọt ngào.',
    'A small pastel mix bouquet with vivid pink blooms in black wrap, modern and sweet.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Vừa 1',
    'Medium Pastel Mix Bouquet 1',
    850000,
    'Bó pastel mix size vừa với hồng, gerbera và hoa nhỏ xanh vàng, mềm mại như một khu vườn nhỏ.',
    'A medium pastel mix with roses, gerberas, and tiny blue-yellow accents, soft like a small garden.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Vừa 2',
    'Medium Pastel Mix Bouquet 2',
    850000,
    'Bó pastel mix size vừa tông hồng kem trong giấy gói đen, nhẹ nhàng và nổi bật.',
    'A medium pastel mix in pink and cream tones with black wrap, gentle and striking.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Vừa 3',
    'Medium Pastel Mix Bouquet 3',
    850000,
    'Bó pastel mix size vừa phối hồng phấn, hoa trắng và điểm xanh lam, thanh thoát trong giấy gói trắng.',
    'A medium pastel mix with blush blooms, white flowers, and blue accents in clean white wrap.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Vừa 4',
    'Medium Pastel Mix Bouquet 4',
    850000,
    'Bó pastel mix size vừa tông đào kem, phối hoa trắng nhẹ và giấy gói hồng nhạt.',
    'A medium pastel mix in peach and cream, finished with soft white accents and pale pink wrap.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Lớn 1',
    'Large Pastel Mix Bouquet 1',
    1000000,
    'Bó pastel mix size lớn tông tím hồng, phối hoa trắng và nơ hồng mềm mại.',
    'A large pastel mix in lilac and blush tones, paired with white blooms and a soft pink ribbon.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Lớn 2',
    'Large Pastel Mix Bouquet 2',
    1000000,
    'Bó pastel mix size lớn tông hồng rực, phối hồng kem, hoa trắng và nơ trắng xinh.',
    'A large pastel mix with bright pink blooms, cream roses, white flowers, and a sweet white ribbon.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Lớn 3',
    'Large Pastel Mix Bouquet 3',
    1000000,
    'Bó pastel mix size lớn tông hồng kem, điểm hoa trắng tinh khôi và giấy gói hồng nhẹ.',
    'A large pastel mix in pink and cream tones, accented with clean white flowers and soft pink wrap.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  ),
  (
    'Bó Pastel Mix Size Lớn 4',
    'Large Pastel Mix Bouquet 4',
    1000000,
    'Bó pastel mix size lớn phối hồng, kem và xanh non, rạng rỡ cho lời chúc thật vui.',
    'A large pastel mix of pink, cream, and fresh green blooms, bright and joyful for congratulations.',
    'Regular Bouquets',
    'Bo Hoa Mix',
    true,
    false,
    true
  );
